name: qyre_test_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  injectable: ^1.5.3
  intl: ^0.17.0
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/raster/
    - assets/images/vector/

  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/matter/Matter-Regular.woff
          weight: 400
          style: normal 
        - asset: assets/fonts/matter/Matter-Medium.woff
          weight: 500
          style: normal
        - asset: assets/fonts/matter/Matter-SemiBold.woff
          weight: 600
          style: normal   
        - asset: assets/fonts/matter/Matter-Bold.woff
          weight: 700
          style: normal
        - asset: assets/fonts/matter/Matter-Bold.woff
          weight: 900
          style: normal
    
